# Generated by Django 4.0.5 on 2024-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_id', models.IntegerField()),
                ('Name', models.TextField()),
            ],
        ),
    ]
